language: python
python:
  - "2.7"
# command to install dependencies
install: "pip install -r requirements.txt"
# command to run tests
script:
  - coverage run --source=BattleShips setup.py test
  - coverage report -m
branches:
  only:
    - master
after_success:
  - coveralls